# Generated by Django 3.2.7 on 2021-09-29 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128, verbose_name='título')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='notes.notescategory', verbose_name='categoría padre')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('exercises', 'Exercises'), ('practical_exercises', 'Practical Exercises'), ('exams', 'Exams')], max_length=24, verbose_name='tipo')),
                ('year', models.CharField(max_length=8, verbose_name='curso académico')),
                ('file', models.FileField(blank=True, null=True, upload_to='notes/', verbose_name='fichero')),
                ('link', models.CharField(max_length=250, verbose_name='enlace')),
                ('is_visible', models.BooleanField(default=False, verbose_name='es visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.notescategory', verbose_name='categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_notes', 'New Notes'), ('feedback', 'Feedback')], max_length=16, verbose_name='tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='notes.notes', verbose_name='apuntes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_alerts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
